config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :courses do
    get '/help', to: 'courses#help'
    post '/enroll', to: 'courses#enroll'
    delete '/unenroll', to: 'courses#unenroll'
    post '/invite', to: 'courses#invite'
    post '/change-admin', to: 'courses#change_admin'
    post '/change-staff', to: 'courses#change_staff'
    delete '/remove-staff/:uid', to: 'courses#remove_staff'
    resources :questions, except: [:index] do
      post '/help', to: 'questions#help'
      post '/resolve', to: 'questions#resolve'
    end
  end
  resources :users, except: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htmlc
end

app/controllers/courses_controller.rb
# Courses controller
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]
  before_action :set_course_id, only: %i[help enroll unenroll invite
                                         change_admin change_staff remove_staff]
  before_action :authenticate_user
  before_action :admin_only, only: %i[invite change_admin change_staff destroy]
  before_action :staff_only, only: %i[edit update]
  before_action :find_user, only: %i[change_admin change_staff remove_staff]

  def index
    @courses = Course.all
  end

  def show; end

  def new
    @course = Course.new
  end

  def edit
    @users = User.all
  end

  def create
    @course = Course.new(course_params)
    @course.add_admin(current_user)
    if @course.save
      redirect_to @course
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        notice = 'Course was successfully updated.'
        format.html { redirect_to edit_course_path(@course), notice: notice }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      notice = 'Course was successfully destroyed.'
      format.html { redirect_to courses_url, notice: notice }
      format.json { head :no_content }
    end
  end

  def help
    if current_user.staff?(@course)
      @course.queue.each do |question|
        cqpath = course_question_path(@course, question)
        redirect_to cqpath if question.status == 'Waiting'
      end
    end
    redirect_to @course
  end

  def enroll
    return if current_user.student?(@course)
    return if current_user.staff?(@course)
    current_user.enroll(@course)
    redirect_back fallback_location: @course
  end

  def unenroll
    current_user.unenroll(@course)
    redirect_back fallback_location: @course
  end

  def invite
    params[:invites].each do |uid|
      user = User.find(uid)
      if user
        staff = Staff.find_by(user: user, course: @course)
        Staff.create(user: user, course: @course, admin: false) unless staff
      end
    end
    notice = 'Successfully invited users to staff.'
    redirect_to edit_course_path(@course), notice: notice
  end

  def change_admin
    redirect_to edit_course_path(@course) unless @user
    staff = Staff.find_by(user: @user, course: @course)
    redirect_to edit_course_path(@course) unless staff
    staff.update(admin: true)
    notice = "Promoted #{@user.name} to an admin."
    redirect_to edit_course_path(@course), notice: notice
  end

  def change_staff
    redirect_to edit_course_path(@course) unless @user
    staff = Staff.find_by(user: @user, course: @course)
    redirect_to edit_course_path(@course) unless staff
    staff.update(admin: false)
    notice = "Removed admin status from #{@user.name}."
    redirect_to edit_course_path(@course), notice: notice
  end

  def remove_staff
    if params[:uid] != current_user.id
      @course.remove_staff(@user) if @user
      redirect_to edit_course_path(@course), notice:
        "Removed #{@user.name} from staff."
    else
      @course.remove_staff(current_user)
      redirect_to @course, notice:
        "Successfully left the staff for #{@course.name}."
    end
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def find_user
    @user = User.find(params[:uid])
  end

  def set_course_id
    @course = Course.find(params[:course_id])
  end

  def admin_only
    return unless current_user.admin?(@course)
  end

  def staff_only
    redirect_to @course unless current_user.staff?(@course)
  end

  def course_params
    params.require(:course).permit(:name, :description)
  end
end

app/views/courses/_edit_form.html.erb
<%= form_with(model: course, local: true, class: 'ui form') do |form| %>

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name, id: :course_name %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_area :description, id: :course_description %>
</div>

<div class="actions">
  <%= form.submit 'Save', class: 'ui sky button' %>
  <%= link_to 'Cancel', @course, class: 'ui button' %>
  <% if current_user.admin?(@course) %>
    <%= link_to 'Delete', @course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui google plus button' %>
  <% end %>
</div>

<% if course.errors.any? %>
  <% class_name = course.class.name.downcase %>
  <% course.errors.keys.each do |field| %>
      <% if course.errors[field].any? %>
        <%= javascript_tag do %>
          document.getElementById('<%= "#{class_name}_#{field}" %>').parentElement.parentElement.classList.add('error');
        <% end %>
      <% end %>
  <% end %>

  <div id="error_explanation" class="ui red message">
    <ul class="list">
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% end %>

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true, class: 'ui form') do |form| %>

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name, id: :course_name %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_area :description, id: :course_description %>
</div>

<div class="actions">
  <% if current_page?(new_course_path) %>
    <%= form.submit 'Create Course', class: 'ui sky button' %>
    <%= link_to 'Cancel', courses_path, class: 'ui button' %>
  <% else %>
    <%= form.submit 'Save', class: 'ui sky button' %>
    <%= link_to 'Cancel', @course, class: 'ui button' %>
    <%= link_to 'Delete', @course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui google plus button' %>
  <% end %>

</div>

<% if course.errors.any? %>
  <% class_name = course.class.name.downcase %>
  <% course.errors.keys.each do |field| %>
      <% if course.errors[field].any? %>
        <%= javascript_tag do %>
          document.getElementById('<%= "#{class_name}_#{field}" %>').parentElement.parentElement.classList.add('error');
        <% end %>
      <% end %>
  <% end %>

  <div id="error_explanation" class="ui red message">
    <ul class="list">
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% end %>

app/views/courses/_staff.html.erb
<table class="ui selectable table">
  <thead>
    <tr>
      <th>Staff</th>
    </tr>
  </thead>
  <tbody>
    <% @course.staffs.each do |staff| %>
    <tr onclick="window.location='<%= user_path(staff.user) %>'">
      <td><%= staff.user.name %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/edit.html.erb
<%= render 'layouts/nav' %>

<div class="ui grid container">
  <div class="centered row" style="margin-top: 48px;">
    <div class="twelve wide column">
      <%= render 'layouts/notice' %>
      <div class="ui segment" style="padding: 40px 48px 36px 48px;">
        <h2 class="ui header">
          Course Settings
          <div class="sub header">
            Update course description and manage staff members
          </div>
        </h2>
        <h4 class="ui dividing header">Course Description</h4>
        <%= render 'edit_form', course: @course %>

        <h4 class="ui dividing header">Manage Staff</h4>
        <%= form_tag course_invite_path(@course), method: 'post' do %>
          <%= select_tag 'invites', options_from_collection_for_select(@users, 'id', 'name_email'), multiple: true, prompt: 'Search by name or email', class: 'ui search dropdown' %>
          <%= submit_tag 'Send Invite', class: 'ui button' %>
        <% end %>
        <table class="ui collapsing table">
        <tbody>
          <% @course.staffs.each do |staff| %>
            <tr>
              <td><%= staff.user.name %></td>
              <td>
                <i class="mail icon"></i>
                <%= staff.user.email %>
              </td>
              <td>
                <% if current_user.admin?(@course) && staff.user.id != current_user.id %>
                <select class="ui fluid small dropdown admin-staff" data-id="<%= staff.user.id %>">
                  <% if staff.admin %>
                    <option value="admin" selected="selected">Admin</option>
                    <option value="staff">Staff</option>
                  <% else %>
                    <option value="admin">Admin</option>
                    <option value="staff" selected="selected">Staff</option>
                  <% end %>
                </select>
                <% else %>
                  <% if staff.admin %>
                    Admin
                  <% else %>
                    Staff
                  <% end %>
                <% end %>
              </td>
              <td>
                <% if current_user.staff?(@course) && staff.user.id == current_user.id %>
                  <%= link_to 'Leave staff', "remove-staff/#{staff.user.id}", method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui red tiny basic button' %>
                <% elsif current_user.admin?(@course) %>
                  <%= link_to 'Remove from staff', "remove-staff/#{staff.user.id}", method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui red tiny basic button' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function () {
  $('.admin-staff').dropdown({
    onChange: function(val) {
      var staffId = $(this).find('select').data('id')
      console.log(staffId)
      $.ajax({
        url: '/courses/<%= @course.id %>/change-' + val,
        type: 'POST',
        data: {
          uid: staffId
        },
        success: function() {
          location.reload()
        }
      })
    }
  })
})
</script>

app/views/courses/index.html.erb
<%= render 'layouts/nav' %>

<div class="ui grid container">
  <div class="centered row" style="margin-top: 36px;">
    <div class="sixteen wide column">
      <%= render 'layouts/notice' %>

      <h2 class="ui header">
        Courses
        <div class="sub header">
          Search for courses and view their office hour queues
        </div>
      </h2>

      <%= link_to 'New Course', new_course_path, class: 'ui sky button' %>
      <div class="ui icon input">
        <input id="course-search" type="text" placeholder="Search courses">
        <i class="search icon"></i>
      </div>

      <table class="ui unstackable table">
        <thead>
          <tr>
            <th class="three wide">Name</th>
            <th class="twelve wide">Description</th>
            <th class="one wide"></th>
          </tr>
        </thead>
        <tbody>
          <% @courses.each do |course| %>
            <tr>
              <td class="searchable-td"><%= course.name %></td>
              <td class="searchable-td"><%= course.description %></td>
              <td><%= link_to 'View', course, class: 'ui button' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script type="text/javascript">
  // the following code snippet was taken from CSS tricks
  $.expr[':'].icontains = $.expr.createPseudo(function (text) {
    return function (e) {
      return $(e).text().toUpperCase().indexOf(text.toUpperCase()) >= 0;
    };
  });

  $('#course-search').keyup(function () {
    var searchText = $(this).val();
    if (searchText.length > 0) {
      $('tbody .searchable-td:icontains(' + searchText + ')').addClass('positive');
      $('.searchable-td.positive').not(':icontains(' + searchText + ')').removeClass('positive');
      $('tbody td').not(':icontains(' + searchText + ')').closest('tr').addClass('hidden').hide();
      $('tr.hidden:icontains(' + searchText + ')').removeClass('hidden').show();
    } else {
      $('.searchable-td.positive').removeClass('positive');
      $('tr.hidden').removeClass('hidden').show();
    }
  });
</script>

app/views/courses/new.html.erb
<%= render 'layouts/nav' %>

<div class="ui grid container">
  <div class="centered row" style="margin-top: 48px;">
    <div class="twelve wide column">
      <div class="ui segment" style="padding: 40px 48px 36px 48px;">
        <div class="sixteen wide column">
          <h2 class="ui header">
            New Course
            <div class="sub header">
              Create an office hours queue for a new course
            </div>
          </h2>
          <%= render 'form', course: @course %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/show.html.erb
<%= render 'layouts/nav' %>

<div class="ui grid container">
  <div class="centered row" style="margin-top: 48px;">
    <div class="twelve wide column">
      <%= render 'layouts/notice' %>

      <div class="ui segment" style="padding: 40px 48px 36px 48px;">
        <h2 class="ui header">
          <%= @course.name %>
        </h2>

        <p>
          <%= @course.description %>
        </p>

        <% if current_user.staff?(@course) %>
          <%= link_to 'Help', course_help_path(@course), class: 'ui sky button' %>
          <%= link_to 'Dashboard', edit_course_path(@course), class: 'ui button' %>
        <% elsif current_user.student?(@course) %>
          <%= link_to 'New Question', new_course_question_path(@course), class: 'ui sky button' %>
          <%= link_to 'Unenroll', "/courses/#{@course.id}/unenroll", method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui button' %>
        <% else %>
          <%= link_to 'Enroll', "/courses/#{@course.id}/enroll", method: :post, class: 'ui button' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="centered row">
    <div class="nine wide column">
      <%= render 'questions/queue' %>
    </div>
    <div class="three wide column">
      <%= render 'courses/staff' %>
    </div>
  </div>
</div>